# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
services:
  shopingmodular-app:
    image: shopingmodularapi
    build:
      context: ./src
      dockerfile: Application/Shoping.Modular.API/Dockerfile
    networks:
      - shopingmodular
    depends_on:
      - shopingmodular-db
    ports:
      - 5221:5221
  shopingmodular-db:
    image: postgres:17.2-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopingmodular
    ports:
      - "5470:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shopingmodular
  shopingmodular-seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      SEQ_API_KEY: "Gi71vBZTn78fXZC1rhPWwg=="
    networks:
      - shopingmodular
    ports:
      - "5341:5341"
      - "9091:80"
  shopingmoduler-redis:
    image: redis:latest
    networks:
      - shopingmodular
    ports:
      - "6379:6379"
  shopingmoduler-rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    networks:
      - shopingmodular
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
networks:
  shopingmodular:
    driver: bridge
volumes:
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local
