# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  shopingmodularapi:
    image: shopingmodularapi
    build:
      context: .
      dockerfile: src/Application/Shoping.Modular.API/Dockerfile
    ports:
      - 5221:5221
